### ISSUE TITLE
Error in hexbin

### ISSUE THREAD

**Issue by gonzalorondinone** [robert-frey/YouTube#1]
Dear Robert, Great content! I´ve been trying to run your code but it get the following error ¿Any idea or help?

SpatialBall::ShotSeasonGraphPlayer(Kobe, player = "Kobe Bryant", type = "PCT")

Error in hexbin(df$LOC_X, df$LOC_Y, 25, xbnds = xbnds, ybnds = ybnds,  : 
  xbnds[1] < xbnds[2] is not fulfilled
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf

**Comment by robert-frey** [comment]
Could I see more code if possible? I want to have a better idea of where the error is rendering.

**Comment by gonzalorondinone** [comment]
Of Course

> library("nbastatR")
There were 27 warnings (use warnings() to see them)
> 
> seasons= c(1997:2016)
> kobeseasons <- list()
> for (i in seq_along(seasons)) {
+   kobeseasons[[i]] = teams_shots(teams = "Los Angeles Lakers",
+                                  seasons= seasons[i])
+ }
Los Angeles Lakers 1996-97 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 1997-98 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 1998-99 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 1999-00 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2000-01 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2001-02 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2002-03 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2003-04 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2004-05 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2005-06 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2006-07 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2007-08 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2008-09 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2009-10 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2010-11 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2011-12 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2012-13 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2013-14 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2014-15 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
Los Angeles Lakers 2015-16 shot data
Joining, by = c("nameTeam", "slugSeason", "idPlayer", "idTeam", "numberTable")
There were 50 or more warnings (use warnings() to see the first 50)
> 
> #load libraries and create one big data frame
> library(tidyverse)
> library(plyr)
> Kobe = ldply(kobeseasons, data.frame)
> 
> #filter data frame by Kobe
> Kobe = Kobe %>% filter(namePlayer == "Kobe Bryant") %>% select(-slugSeason)
> 
> 
> library(SpatialBall)
> 
> #load 2017 season data from SpatialBall package to see what columns are needed
> data2017 = season2017
> 
> #check column names and match Kobe's to the data2017
> colnames(data2017)
 [1] "GRID_TYPE"           "GAME_ID"             "GAME_EVENT_ID"       "PLAYER_ID"           "PLAYER_NAME"        
 [6] "TEAM_ID"             "TEAM_NAME"           "PERIOD"              "MINUTES_REMAINING"   "SECONDS_REMAINING"  
[11] "EVENT_TYPE"          "ACTION_TYPE"         "SHOT_TYPE"           "SHOT_ZONE_BASIC"     "SHOT_ZONE_AREA"     
[16] "SHOT_ZONE_RANGE"     "SHOT_DISTANCE"       "LOC_X"               "LOC_Y"               "SHOT_ATTEMPTED_FLAG"
[21] "SHOT_MADE_FLAG"      "GAME_DATE"           "HTM"                 "VTM"                
> colnames(Kobe)
 [1] "yearSeason"       "idTeam"           "idPlayer"         "typeGrid"         "namePlayer"       "nameTeam"        
 [7] "typeEvent"        "typeAction"       "typeShot"         "dateGame"         "slugTeamHome"     "slugTeamAway"    
[13] "idGame"           "idEvent"          "numberPeriod"     "minutesRemaining" "zoneBasic"        "nameZone"        
[19] "slugZone"         "zoneRange"        "locationX"        "locationY"        "secondsRemaining" "distanceShot"    
[25] "isShotAttempted"  "isShotMade"      
> 
> #Change Kobe names
> names(Kobe) = c("TEAM_ID","PLAYER_ID","GRID_TYPE","PLAYER_NAME","TEAM_NAME","EVENT_TYPE","ACTION_TYPE",
+                 "SHOT_TYPE","GAME_DATE","HTM","VTM","GAME_ID","EVENT_ID","PERIOD","MINUTES_REMAINING",
+                 "SEASON","SHOT_ZONE_BASIC","SHOT_ZONE_AREA","SHOT_ZONE_AREA_ABBR","SHOT_ZONE_RANGE",
+                 "LOC_X","LOC_Y","SECONDS_REMAINING","SHOT_DISTANCE","SHOT_ATTEMPTED_FLAG","SHOT_MADE_FLAG")
> 
> #Convert T/F to 1 and 0 in Kobe data frame
> Kobe$SHOT_ATTEMPTED_FLAG = ifelse(Kobe$SHOT_ATTEMPTED_FLAG == TRUE, 1, 0)
> Kobe$SHOT_MADE_FLAG = ifelse(Kobe$SHOT_MADE_FLAG == TRUE, 1, 0)
> 
> #Kobe's Hex chart expressed as a Percentage
> SpatialBall::ShotSeasonGraphPlayer(Kobe, player = "Kobe Bryant", type = "PCT")
Error in hexbin(df$LOC_X, df$LOC_Y, 25, xbnds = xbnds, ybnds = ybnds,  : 
  xbnds[1] < xbnds[2] is not fulfilled
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf

**Comment by robert-frey** [comment]
I see the issue, your column names are 1 to the left, meaning player ID is listed as grid type in your code. Remove "yearSeason" from the Kobe data.frame and the rename the columns again and it should work. Let me know.

**Comment by gonzalorondinone** [comment]
Yes! That is right! I think I also need to erase one more column from Kobe but I dont know wich one, sorry for bothering but Im really learning here!

**Comment by gonzalorondinone** [comment]
Hey Robert! I just wanted to let you know that I made it! Thanks a lot! I will try to replicate with another player!
